spioupiou/de-bored

app/models/game.rb, app/models/games_datum.rb, app/models/lobby.rb, app/models/player.rb, app/models/player_input.rb, db/migrate/20220211011130_create_games.rb, db/migrate/20220211011136_create_lobbies.rb, db/migrate/20220211011252_create_games_data.rb, db/migrate/20220211011333_create_players.rb, db/migrate/20220211011559_create_player_inputs.rb, db/schema.rb, test/models/game_test.rb, test/models/games_datum_test.rb, test/models/lobby_test.rb, test/models/player_input_test.rb, test/models/player_test.rb
made the models/migration files + basic associations has_many/has_many :through. Please let me know if you see any issue :)
=> Initial commit for models

app/models/game.rb, app/models/games_datum.rb, app/models/player_input.rb
Basic validations - for input_type I am not sure if we should go for string/bool/int or something else ("phrase" for example) Let me know what you think!
=> Basic validations

config/routes.rb
=> Routes are done

app/controllers/instances_controller.rb, app/controllers/pages_controller.rb, app/controllers/player_inputs_controller.rb, app/models/instance.rb, app/views/pages/home.html.erb, test/controllers/instances_controller_test.rb, test/controllers/player_inputs_controller_test.rb
- Created the controllers and empty CRUD methods for instances and player_inputs
- Deleted the pages_controller and pages_views (we don't need it because our home page is the index of games, if we need other independent pages later on we can always recreate it)
=> Make controllers

app/views/games/index.html.erb
=> this is only Temporary, to visualize the view of our game-index page

db/seeds.rb, db/seeds/games_contents_seeds.rb, db/seeds/users_seeds.rb
Seeds again because the changes are not reflected on master (T__T) This is probably because I deleted those three files on another branch that was merged after basic-seeds branch aaah
=> Seeds again

app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
ok login/update/registration forms should be better
=> more friendly login/update/register page

app/controllers/instances_controller.rb, app/views/games/index.html.erb, app/views/instances/show.html.erb
New branch without seeds files :)
- User clicks on the game
- If user is not signed in, he's redirected to the sign-in page
- If user is signed in:
> An instance is created with the current_user as a host and game_id as per params[:game_id]
> A new player is created with current_user.id (host.id)
> Host is redirected to Instance show page
I have tested the code and it seems to work pretty well, but please test it out on your machine!
=> Clicking on the game creates an instance

app/controllers/instances_controller.rb, app/controllers/players_controller.rb, app/views/games/index.html.erb, app/views/instances/show.html.erb, config/routes.rb, test/controllers/players_controller_test.rb
FYI - I had to create a new route for the join method in the instance controller (this join method takes a pin submitted by a user as params)
I used 100_000 + instance.id as a pin (I am not sure but I don't think I can start from 0 because the pin column is an integer, if I use 000001 for example, active:record will most likely only record 1 as the pin)
When the lobby is not found, I re-render the page with a flash alert (bottom right corner). 
Of course we can implement AJAX later on but I don't think my front end can get any better than this lol
Would appreciate any feedback! 
https://user-images.githubusercontent.com/68413600/153752747-15548ede-4cd1-4f99-883d-fdb0240cdf99.mov
=> Logic implemented

app/channels/instance_channel.rb, app/controllers/instances_controller.rb, app/javascript/channels/instance_channel.js, app/javascript/packs/application.js, app/views/games/index.html.erb, app/views/instances/show.html.erb, test/channels/instance_channel_test.rb
Added web socket to instance. Check the Chrome console to see if it the connection works properly! 
At the moment, a host can create the lobby and will generate a connection with a new instance number (which is displayed in the Chrome console). Since the [Join game] feature is not created just yet, I did not test to see if someone else can join the same game with the same instance.
=> Websocket setup

app/controllers/instances_controller.rb, app/views/instances/show.html.erb
As per our discussion, have pushed the fix on the dbi create issue.
=> fix on create dbi

app/views/games/index.html.erb
=> Signin fixed

app/models/instance.rb, db/migrate/20220215173042_add_max_players_to_instances.rb
This will be used in our DBI show page before the game starts.
=> migration for adding max players into the game

app/controllers/players_controller.rb
=> Avoid duplicate players

app/channels/application_cable/connection.rb, app/channels/instance_channel.rb, app/controllers/players_controller.rb, app/javascript/packs/application.js, app/models/player.rb, app/views/instances/_show_waiting.erb
We're now able to live update if a new player joins
https://user-images.githubusercontent.com/18746187/154674289-d1236ef3-59c0-4a53-9a09-88b4bd7b6d6c.mov
=> Dbi waiting update all players when a new player joins

app/controllers/application_controller.rb, app/controllers/player_inputs_controller.rb, app/controllers/rounds_controller.rb, app/views/instances/_show_question.erb, app/views/instances/_show_result.erb, app/views/rounds/show.html.erb, config/routes.rb, db/seeds.rb
Good morning team! 
So I've been working on the player_inputs#create and index of player_inputs most of yesterday and it's been VERY painful lol
I found a working solution but it's not ideal.
- A big issue is that web socket doesn't like it when two players try to submit an answer at the same time. One of the player will face a big authenticity token error. I could solve the issue by adding `skip_forgery_protection` in the application controller
- And as you may have noticed: I can't for the life of me render the results in the instance with a partial 😞  Rails always prompt me to create a html.erb. So I temporarily created a show.html.erb in the rounds controller
Anyway at least it's a working solution for the demo today!
https://user-images.githubusercontent.com/68413600/154769412-adc0142 …
=> A working but not elegant solution

config/cable.yml
=> setup for action cable in prod

app/views/instances/_show_result.erb, app/views/rounds/show.html.erb
=> result color fixed

app/views/shared/_navbar.html.erb
=> logo to root

app/controllers/instances_controller.rb, app/models/round.rb
=> Some cleanup

app/controllers/players_controller.rb, app/javascript/channels/instance_channel.js, app/views/instances/_player_list.erb, app/views/instances/_show_waiting.erb
I think I fixed this one but test on you local first before merging
=> start btn wont show except for host

app/views/rounds/show.html.erb
So master still had the old version of show.html.erb for some reasons.
Now it works :D
=> Found the bug

app/controllers/rounds_controller.rb, app/views/rounds/show.html.erb
A simple end game button that is visible to everyone, when user clicks the button he is redirected to a completely new instance.
=> Working end button

app/controllers/players_controller.rb, app/controllers/rounds_controller.rb, app/javascript/channels/instance_channel.js
We're now able to redirect all players to a different page. We can recycle this method for next rounds and end game.
https://user-images.githubusercontent.com/18746187/154990392-2dea3bb5-c14a-4d77-97fa-6aaa5ac9cd00.mov
=> Redirect all players to rounds phase1 after starting the game

app/controllers/rounds_controller.rb, app/javascript/channels/round_channel.js, app/views/rounds/show.html.erb
Not the best code I did, I don't even know how to get the `@round` element from the controller so I Improvise haha. If you have better code please feel free to change this
https://user-images.githubusercontent.com/79787121/155036401-391851f7-0864-47fd-b901-80cfc9b511cc.mp4
=> loop rounds when continue button is clicked

app/javascript/packs/application.js, app/javascript/packs/rough_notation.js
=> fixes for action cable

app/views/rounds/show.html.erb
=> as per Carl's suggestion

app/controllers/player_inputs_controller.rb, app/models/player_input.rb, app/views/rounds/_show_question.erb
It looks like replacing the link_to with proper simple_forms solve the issue of multiple player_inputs :) I tried to click several times on the button and the bug was gone.
I also added some validation and a flash alert if the same user tries to submit an answer twice
https://user-images.githubusercontent.com/68413600/155287794-44e44478-af67-4a3e-8c7e-0b8b56c7c0f0.mov
=> Fix for several answers from same player

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_modal.scss, app/assets/stylesheets/components/_scrollbar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/instance.scss, app/controllers/player_inputs_controller.rb, app/javascript/channels/round_channel.js, app/views/components/_modal.html.erb, app/views/components/_nickname_modal.html.erb, app/views/games/index.html.erb, app/views/instances/_instance_update_form.html.erb, app/views/instances/_show_game_settings.html.erb, app/views/instances/_update_modal.html.erb, app/views/player_inputs/_player_input.html.erb, app/views/rounds/show.html.erb
Styled some UIs play with it before merging!
https://user-images.githubusercontent.com/79787121/155624757-6ac7866d-2fdd-4ea2-a1d6-e21db117091e.mp4
=> done with the styling but can be improved

app/views/rounds/_show_question.erb, app/views/rounds/show.html.erb, db/seeds/game_contents_seeds.rb
I changed the questions from "Never Have I ever" to "Have you ever" so that it is clearer.
I kept the game title as "Never have I ever", we just changed the way questions are phrased for clarity but it doesn't mean that the concept of the game has changed :) Of course we can amend later with a badass name if we need!
I also put back the normal seeds + added a few new ones.
=> Clarified questions and new seeds

app/controllers/application_controller.rb, app/views/shared/_navbar.html.erb, db/migrate/20220225022216_add_guest_to_users.rb
As discussed yesterday, I added a flag for guest_users and fixed the navbar accordingly :)
=> Fixed the login-logout

app/controllers/rounds_controller.rb, app/views/rounds/show.html.erb
If/Else statements forever!!
https://user-images.githubusercontent.com/68413600/155659973-08ac8a69-9a04-42c1-b020-431672e05a03.mov
=> Next round button replaced by Exit game at last round

app/controllers/application_controller.rb
=> change guest to player

app/views/rounds/_show_question.erb, app/views/rounds/show.html.erb
https://user-images.githubusercontent.com/79787121/155815040-aeba5633-c6e7-4e6a-995a-6921a4fbb3c3.mp4
=> Minor UI change

app/views/games/index.html.erb, db/seeds.rb
@hiroya210 @spioupiou , this works locally, need to check in prod, can you please merge 🙏🏼
=> show images in prod

app/views/games/index.html.erb
missed gradient while fixing images in prod
=> adding gradient back and lignment cleanup

db/migrate/20220226131751_add_imposter_to_players.rb
=> Migration for imposter

app/controllers/instances_controller.rb, app/views/instances/_show_waiting.erb, app/views/rounds/show.html.erb, db/migrate/20220227011314_change_default_of_max_rounds.rb, lib/custom_classes/passcode.rb
- we are now able to preserve last instance settings
- major cleanup on instance#create to make it easy to add new features later on
https://user-images.githubusercontent.com/18746187/155866376-14087b20-2ae7-4849-8082-a3f144ace526.mov
=> Preserve instance settings on new instance + Refactor instance creation

app/controllers/instances_controller.rb
small fix, ensure to update instance status to "done" after last round
=> updates instance status after last round

app/controllers/player_inputs_controller.rb, app/controllers/rounds_controller.rb, app/models/instance.rb
The method `non_host_player_user_ids` is no longer needed.
=> cleaning up

app/views/instances/_show_game_settings.html.erb
=> Impostor always true

app/controllers/rounds_controller.rb, db/migrate/20220301045230_change_imposter_to_impostor_in_players.rb, db/migrate/20220301122042_add_impostor_to_instance.rb
I started to implement the impostor feature (backend only for now!)
- if the instance has no rounds yet (e.g. it's the very start of the game), I call a function called generate_impostor
- this function will make the first user with nickname "cedrine" the impostor
- if no player with the nickname "cedrine" is found, then the impostor is assigned randomly (using our favorite array.sample ❤️ )
I also changed the column_name from imposter to impostor, apparently both spellings can be found but impostor seems to be the correct spelling 😮 
https://writingexplained.org/imposter-or-impostor-spelling
https://user-images.githubusercontent.com/68413600/156110611-8d09d384-9164-4a60-a799-c18ff241adde.mov
=> backend setup for impostor

app/controllers/instances_controller.rb, app/controllers/players_controller.rb, app/javascript/channels/instance_channel.js, app/views/instances/_player_list.erb, app/views/instances/_show_waiting.erb, app/views/instances/show.html.erb, config/routes.rb
Added Back button for Hosts and players: 
https://user-images.githubusercontent.com/79787121/156244656-c70a6c17-f4c5-410c-8502-0b14b80d3d97.mp4
Take note that: 
- if a Host click the "back button" of the BROWSER, instance will be deleted but players will not be redirected
- if a player also click "back button" his/her player object wont be deleted.
=> added back button for host and players

app/javascript/components/auto_focus.js, app/javascript/packs/application.js, app/views/components/_modal.html.erb, app/views/components/_nickname_modal.html.erb
As mention [here](https://lewagon-alumni.slack.com/archives/C02P394JVNK/p1646179845119269) the modal has autofocus on mobile now but the animation is gone. sooo we need to decide what to prioritize
=> auto focus on modal but no more animation

app/controllers/instances_controller.rb, app/controllers/players_controller.rb, db/migrate/20220303010005_add_nickname_to_players.rb
Quick implementation so that our lives will be much easier later on :)
=> Nicknames on players table

app/controllers/instances_controller.rb, app/controllers/votes_controller.rb, app/views/results/index.html.erb, app/views/rounds/_show_answers.html.erb, app/views/votes/new.html.erb, config/routes.rb
I improved the voting/results pages + corrected a bug for the players nickname:
-- Votes_controller: renamed the #redirect method to #redirect_to_vote, I also changed the route so that it is clearer
-- No more hidden round passed in the redirect_to_vote form (instead I look for the latest round created in the votes_controller)
-- Both votes page and results page clearly show the nicknames of the players 
-- I assigned nicknames to players in the create_players_from_previous_instance method as well (otherwise players will be created without nicknames in the next instance and their nicknames will not appear in the voting/results page)
<Results>
<Vote new>
=> Voting page

app/javascript/components/countdown_timer.js, app/javascript/packs/application.js, app/views/rounds/_show_impostor.html.erb
https://user-images.githubusercontent.com/79787121/156522458-c6abeeb1-c21e-4dd1-be53-69ccd6df062e.mp4
=> Timer redirect

Gemfile.lock
On ticket, Ryan will review this PR.
=> need for pushing to heroku

Gemfile.lock
In a Ticket with Ryan, will merge directly.
=> change platform on gemfile.lock

app/controllers/player_inputs_controller.rb, app/javascript/channels/round_channel.js, app/views/rounds/_show_answers.html.erb, app/views/rounds/_show_player_inputs_count.html.erb
https://user-images.githubusercontent.com/79787121/156533421-ac68a78e-35a1-42ef-99b3-ac9ed1e2a4c9.mp4
=> Player count result

app/views/layouts/application.html.erb
=> font on prod, added via stylesheet_pack_tag

app/controllers/instances_controller.rb, app/controllers/results_controller.rb, app/controllers/votes_controller.rb, app/javascript/channels/result_channel.js, app/views/results/show.html.erb, app/views/rounds/_show_answers.html.erb
Yaaaaaaaaaaaay thank you @carlnoval!!
=> Move end button at the end

package.json
Merge this to fix master please 🙏🏼
=> yarn install to fix route issue

app/controllers/votes_controller.rb, app/views/results/_share_modal.html.erb, app/views/results/show.html.erb, app/views/votes/new.html.erb
A small if/else statement so that the player cannot vote for himself.
I also fixed the problem placement of End Game/Share buttons in the results page + made sure that those two buttons are ignored when the screenshot is taken.
=> Player can't vote for himself

app/views/results/_result_chart.html.erb
=> Putting the chart code in partial

app/views/components/_nickname_modal.html.erb, app/views/players/_popup_modal.html.erb, app/views/results/show.html.erb, app/views/rounds/_show_answers.html.erb, app/views/rounds/_show_question.html.erb, db/seeds.rb
Minor string updates, should be a quick review.
=> string changes

Gemfile.lock
=> needed for prod push

app/views/results/_share_modal.html.erb
=> Fix logo on production

config/environments/production.rb
=> prod fix for images

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_slider.scss, app/views/instances/_instance_update_form.html.erb
Added an Imposter slider to the game setting.
=> added sliders

app/controllers/player_inputs_controller.rb
Soooo it was because when I made the create in player_inputs controller, I used "find_by_user_id" to retrieve the player... I didn't realize that we create players every single time an instance is generated. So my find_by was only getting the first player created with the current_user.id 🤣 
I am not sure if that's clear so here are some screenshots to explain what my poor tired brain wants to say lol
=> Buuuuuuuuug fix

Gemfile, Gemfile.lock, app/models/player.rb, app/models/user.rb, config/environments/production.rb, config/storage.yml, db/migrate/20220305090926_create_active_storage_tables.active_storage.rb
For our avatars!
- Please note that both the **Gemfile** and **Gemfile.lock** are required for this PR. This is so we won't have problems pushing to production.
=> Cloudinary setup

Gemfile, Gemfile.lock
Apologies, I forgot to remove this gem from my previous PR. This is was one of the things I was playing around with. We won't end up using this gem though.
=> remove avatarly

app/models/user.rb
It was tough finding the right background that works well with all the robot's color possibilities. This is the best I've found so far.
=> added more options for background on avatars

Gemfile
One simple change, need to check if our avatars do work on prod.
=> make sure 'open-uri' gets added to both dev and prod

app/views/games/index.html.erb
Small bugfix on the bug I've created last time.
=> make sure that madlibs also gets the [comming soon] remark

app/models/user.rb
small fix, cause I am a master of small fixes, sorry guys 😅
=> fix erroneous comment

app/assets/stylesheets/pages/_result.scss, app/controllers/votes_controller.rb, app/javascript/channels/result_channel.js, app/views/instances/_player_list.erb, app/views/player_inputs/_player_input.html.erb, app/views/results/_result_chart.html.erb, app/views/results/_result_who_voted.html.erb, app/views/results/show.html.erb
Implement websocket in result instance
applied the avatars big thanks to @carlnoval!
https://user-images.githubusercontent.com/79787121/156961634-ef053538-c364-423c-881c-fe15523f8741.mp4
=> Result page

app/assets/config/manifest.js, app/assets/stylesheets/components/_avatar.scss, app/models/user.rb, app/views/instances/_player_list.erb, app/views/player_inputs/_player_input.html.erb, app/views/results/_result_chart.html.erb, app/views/shared/_navbar.html.erb
For the meantime I added border and change the bg, I notice some of bots here has light color, so lets go with darker bg For now
=> Avatar border

app/views/layouts/application.html.erb, config/meta.yml
Added our very own twitter account @de_bored_
=> Updated tags with our twitter account

app/controllers/votes_controller.rb
For some reason we were still creating several results (every time a new vote was made) 
I think I solved the bug but let me know if there is a better syntax 😄
=> Only one result is created for the instance

public/404.html, public/500.html
This is for more checks on [Product Demo Checklist](https://kitt.lewagon.com/products/7876). If you'd like to see these in action in your local:
- In #config/environments/development.rb, set `config.consider_all_requests_local = false`
- Start / restart server
- For 404 just go to any random route
- For 500, put a raise on a controller method and load the view in the browser
=> simple themed error pages for de.bored

config/meta.yml
More ticks for [Product Demo checklist](https://kitt.lewagon.com/products/7876).
=> one more check on product demo checklist

app/assets/stylesheets/components/_logo.scss, app/javascript/plugins/rough_notation.js
I'll add the animations back after [og:image has the right dimensions (1200x630)](https://kitt.lewagon.com/products/7876)
=> disable animation temporarily

app/assets/stylesheets/pages/_impostor.scss, app/views/rounds/_show_impostor.html.erb
=> redesign impostor page

app/views/results/_result_vote_tally.html.erb, app/views/results/show.html.erb
This bug came up due to multiple conflicts that we tried to resolve on the past 10 ish PRs.
=> use the right partial in results tally

app/views/rounds/_show_answers.html.erb, app/views/votes/new.html.erb
I havent tested this with 5 or more players
=> added avatars on vote page

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_speech.scss, app/views/shared/_navbar.html.erb
=> added speech bubble for cuteness :D

app/javascript/components/show_taps.js, app/javascript/packs/application.js
So that the audience can see where we click 😄
Video to show the code in action (only for mobiles)
(I misclicked when I tried to join the instance so don't pay attention to the delay on home page 🤣 )
https://user-images.githubusercontent.com/68413600/157370053-7c737947-2789-48d8-bc76-da26c88ba098.mov
=> Yann's code to show the taps on mobile

Gemfile, Gemfile.lock, app/controllers/screenshots_controller.rb, app/javascript/components/screenshot.js
Our tweets have tiny and functional urls :)
I tweeted a results page for testing, the tweet is available here if you want to check it out!:
https://twitter.com/de_bored_
=> Minify url

app/assets/stylesheets/pages/_result.scss, app/views/games/index.html.erb, app/views/results/_result_stat.html.erb, app/views/results/show.html.erb
Since the result stats looked a bit ugly, I tried to design it just a tad bit. Not too much.
=> added a bit of styling to the results-stats

app/assets/stylesheets/components/_slider.scss, app/views/instances/_instance_update_form.html.erb
Tiny change so that the slider is green + Imposter replaced by Impostor
=> Settings slider

app/views/instances/_impostor_info_modal.html.erb
=> string change

app/assets/stylesheets/components/_modal.scss, app/controllers/players_controller.rb, app/views/instances/_show_game_settings.html.erb
- Passcodes are now shown capitalized (they don't look that bad and still fits on mobile)
- Passcodes are now forced to be upcased when joining a lobby
https://user-images.githubusercontent.com/18746187/157718058-08f44200-68f8-4a00-8998-f76dc3e4a7c5.mov
=> Passcode force upcase

app/views/instances/_instance_update_form.html.erb, config/initializers/simple_form_bootstrap.rb
Closed a previous PR and now reopened with new PR. 
- Removed green checks in game setting menu
- Fixed capitalization in dropdown menu
=> Fixes to the green check and minor fonts

app/views/players/_popup_modal_host.html.erb, app/views/players/_popup_modal_player.html.erb
disable auto-close of modal when we tap/click outside
https://user-images.githubusercontent.com/79787121/157780824-6b1d14dc-d921-4103-a3de-65d08285c5f7.mp4
=> disable modal close when tap/click outside

app/controllers/results_controller.rb, app/views/results/_result_stat.html.erb
=> avatars in stats

app/assets/stylesheets/components/_modal.scss, app/views/results/show.html.erb, app/views/rounds/_show_impostor.html.erb
=> small fixes
